<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xlnZrd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xlnZrd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3xlnZrd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3xlnZrd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3xlnZrd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3xlnZrd',
    'container.build_id' => '027a1f20',
    'container.build_time' => 1566563345,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xlnZrd');
